# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/745dc579-0f6e-4b6d-b4ee-820231616eb1";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/745dc579-0f6e-4b6d-b4ee-820231616eb1";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/745dc579-0f6e-4b6d-b4ee-820231616eb1";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/745dc579-0f6e-4b6d-b4ee-820231616eb1";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/745dc579-0f6e-4b6d-b4ee-820231616eb1";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/745dc579-0f6e-4b6d-b4ee-820231616eb1";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/745dc579-0f6e-4b6d-b4ee-820231616eb1";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/745dc579-0f6e-4b6d-b4ee-820231616eb1";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/77DA-2A45";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1c45008a-8136-421d-99a7-7876db3d713e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
