[backdrop]
enabled = true

[bar.default]
background_opacity = 0.48999998904764652
center = [ "clock" ]
end = [
    "nix-monitor",
    "status",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "battery",
    "control-center",
    "session"
]
start = [ "launcher", "bar", "wallpaper", "wallhaven", "workspaces", "bar_2" ]

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.24999999441206455
enabled = true
launcher_position = "start"
pinned = [
    "org.qutebrowser.qutebrowser",
    "kitty",
    "chrome-jejhhdjidabobmikfdbgjcnbgkcdkfam-Default",
    "chrome-www.messenger.com__-Default",
    "org.kde.dolphin"
]
position = "right"
reserve_space = false
show_dots = true
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "regina, ab"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-2",
    "lockscreen-login-box@DVI-I-1",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@eDP-1"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DVI-I-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 957.0
    output = "DVI-I-1"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DVI-I-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-2"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 957.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugin_settings."avivbintangaringga/nix-monitor"]
hide_update_button = true

[plugin_settings."mindnbytes/nix-status"]
flake_dir = "/etc/nixos"
nixos_configuration = "nixos"

[plugin_settings."noctalia/wallhaven"]
download_dir = ""

[plugins]
enabled = [ "noctalia/wallhaven", "yuuto/calculator", "noctalia/umbriel-companion", "avivbintangaringga/nix-monitor" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
settings_show_advanced = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.panel]
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    directory = "/home/yan/Photos/Wallpaper"
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Gruvbox"
community_palette = "Gruvbox Material"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kitty", "niri", "qt", "starship", "umbriel" ]
    community_ids = [ "qutebrowser", "fastfetch", "lazygit", "yazi" ]

[wallpaper]
directory = "/home/yan/Photos/Wallpaper"

    [wallpaper.default]
    path = "/home/yan/Photos/Wallpaper/wallhaven-qrmlyd.png"

    [wallpaper.last]
    path = "/home/yan/Photos/Wallpaper/wallhaven-qrmlyd.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/yan/Photos/Wallpaper/wallhaven-qrmlyd.png"

[widget.bar]
type = "yuuto/calculator:bar"

[widget.bar_2]
type = "noctalia/umbriel-companion:bar"

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.nix-monitor]
type = "avivbintangaringga/nix-monitor:nix-monitor"

[widget.status]
type = "davemhammer/tailscale:status"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"
